apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gcr.io/chromatic-idea-422815-v2/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "AIzaSyDFQlOm0NEBLruNRqJYqzg9-82Rhkkpf60"
        volumeMounts:
        - name: secret-volume
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: google-cloud-key